apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    name: mysql
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: do276/mysql-55-rhel7
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: r00tpa55 
        - name: MYSQL_USER
          value: user1 
        - name: MYSQL_PASSWORD
          value: mypa55 
        - name: MYSQL_DATABASE
          value: items 
      ports: 
        - containerPort: 3306
          name: mysql
      volumeMounts:
      - mountPath: "/var/lib/mysql/data"
        name: db-volume 
      - mountPath: "/var/lib/mysql/init"
        name: db-init
  volumes:
    - name: db-volume 
      persistentVolumeClaim:
       claimName: dbclaim 
    - name: db-init
      persistentVolumeClaim:
       claimName: dbinit
