apiVersion: v1
kind: Pod
metadata:
  name: todo 
  labels: 
    name: todo
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: do276/todonodejs
      name: todo
      ports: 
        - containerPort: 30080
          nodePort: 30080
          name: nodejs-http 
      env:
        - name: MYSQL_ENV_MYSQL_DATABASE
          value: items
        - name: MYSQL_ENV_MYSQL_USER
          value: user1
        - name: MYSQL_ENV_MYSQL_PASSWORD
          value: mypa55
