apiVersion: v1
kind: Pod
metadata:
  name: ui 
  labels: 
    name: ui
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: do276/todo_frontend
      name: ui 
      ports: 
        - containerPort: 80 
          name: ui 
