apiVersion: v1
kind: Pod
metadata:
  name: todoapi 
  labels: 
    name: todoapi
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: do276/todoapi_php
      name: todoapi
      ports: 
        - containerPort: 8080
          name: php-http 
      env:
        - name: MYSQL_ENV_MYSQL_DATABASE
          value: items
        - name: MYSQL_ENV_MYSQL_USER
          value: user1
        - name: MYSQL_ENV_MYSQL_PASSWORD
          value: mypa55
